data/sideload.desktop.in

Required for #4 but I don't think it's all that's needed to fix it.

Allow passing a file to the .desktop

---

.github/workflows/githubci.yml

Add Lint to CI

---

data/sideload.desktop.in
meson.build
meson/post_install.py

Associate with .flatpakref files

---

src/MainWindow.vala

MainWindow: have agree_check grab focus

---

src/MainWindow.vala

Re: https://github.com/elementary/website/pull/2253

Sentence-case primary dialog label

---

src/Views/ErrorView.vala

Clean up error copy

---

src/FlatpakRefFile.vala

Default to installing software for user, not system

---

meson.build
src/FlatpakRefFile.vala
src/MainWindow.vala
src/Views/SuccessView.vala

Show a view on completed install

---

src/MainWindow.vala

Copy from https://github.com/elementary/sideload/pull/27#issuecomment-536339299

Warn about addition of remotes in copy

---

src/MainWindow.vala
src/Views/ProgressView.vala

Use flatpak status as secondary progress text

---

src/MainWindow.vala

MainWindow: Fix row spacing

---

src/MainWindow.vala
src/Views/SuccessView.vala

Treat already installed as success

---

src/FlatpakRefFile.vala

Calculate overall transaction progress for progressbar

---

src/MainWindow.vala

Fixes #28 
Please check I've done the icon in the notification right. I seem to be having some issues with getting the icon to show anywhere on my system. Probably something I've broken at some point.

Notifications and dock progress

---

src/Application.vala

Close Sideload when opening installed app

---

data/sideload.appdata.xml.in

Add release data ahead of an actual release

AppData: Add release data

---

README.md
meson.build
src/FlatpakRefFile.vala
src/MainWindow.vala
src/Utils/AsyncMutex.vala

Fetch app name from appdata

---

src/MainWindow.vala
src/Views/MainView.vala

MainView: update with app_name when available

---

README.md
meson.build
src/MainWindow.vala

Support dark style preference

---

src/Views/SuccessView.vala

We don't really need to say, "successfully" because that's obvious. So this can be a little simpler. :)

SuccessView: More concise copy

---

data/sideload.desktop.in

Desktop: Add X-GNOME-UsesNotifications

---

src/Views/SuccessView.vala

Closes #113 
Forgot to add this in #110 :disappointed:

Trash flatpakref on app launch

---

src/Views/ProgressView.vala

https://github.com/elementary/files/issues/1567 but for Sideload

ProgressView: Use tabular numbers

---

debian/control

Add Handy to Control

---

src/FlatpakBundleFile.vala
src/FlatpakRefFile.vala

Search for Runtimes in System Remotes too

---

data/sideload.appdata.xml.in

get ahead of translations a couple days

AppData: Update for 6.0.1

---

data/sideload.appdata.xml.in
src/Views/MainView.vala

MainView: update copy

---

src/FlatpakFile.vala
src/FlatpakRefFile.vala
src/MainWindow.vala
src/Views/MainView.vala

I figure we could get a lot more detailed in a future branch, but for now this does the least to let people know broadly what kind of permissions are being requested

Show flatpak permission warning

---

src/Views/SuccessView.vala

Make Open button default widget

---

src/MainWindow.vala

Fix glitches

---

data/sideload.metainfo.xml.in

6.2.1 Release Notes

---

src/Application.vala
src/MainWindow.vala

Move things that should happen app-wide on startup here

Application: use Startup

---

src/MainWindow.vala

Fixes #171 
While we're here some minor clean up

MainWindow: fix invalid bundle cast
